apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  labels:
    app: my-flask-app
spec:
  type: LoadBalancer  # Change to NodePort or ClusterIP as needed
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the service
      targetPort: 5000  # Port your Flask app listens on

